name: Steffi & Michael on tour
author: Steffi & Michael
description: 
url: http://travelblog.mpollmeier.github.io
safe: false
lsi: false
pygments: true
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock']
permalink: pretty
