name: Steffi and Michael on tour
author: Steffi and Michael
description: Steffi and Michael on tour
url: http://travelblog.michaelpollmeier.com
safe: false
lsi: false
pygments: true
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock']
permalink: pretty
